[settings]

load_local = false
remote_repo_url = "https://raw.githubusercontent.com/alwolmer/municipios-dashboard/refs/heads/main/data/bairros_clustered.geojson?token=GHSAT0AAAAAADDJMWC3GAKUBCL4KNXYJP5Y2CAQ37Q"